#!/bin/bash

echo "📱 Android Icon Size Optimization Guide"
echo "======================================"
echo ""
echo "Your adaptive icons have been generated with:"
echo "✅ Background color: #1E40AF (blue)"
echo "✅ Foreground: Your app icon"
echo "✅ Adaptive icon support for Android 8+"
echo ""
echo "🔍 Why icons might appear small on Android:"
echo "1. Adaptive icons use a 'safe area' (66% of total icon)"
echo "2. Your original icon might have padding/whitespace"
echo "3. Different launchers scale icons differently"
echo ""
echo "💡 To make the icon appear larger:"
echo ""
echo "Option 1: Update your source icon"
echo "- Make sure your app_icon.png fills most of the canvas"
echo "- Remove any extra padding/whitespace around the icon"
echo "- The main visual elements should use ~80% of the icon area"
echo ""
echo "Option 2: Use a different background color"
echo "- Current: #1E40AF (blue)"
echo "- Try: Transparent or match your icon's background"
echo ""
echo "Option 3: Create icon-only foreground"
echo "- Create a version with transparent background"
echo "- Place only the main icon elements in foreground"
echo ""
echo "🔄 After updating your icon:"
echo "1. Replace assets/app_icon.png with larger version"
echo "2. Run: flutter pub run flutter_launcher_icons:main"
echo "3. Run: flutter build apk"
echo "4. Install on your Android device"
echo ""
echo "📱 Current APK ready for testing:"
echo "   build/app/outputs/flutter-apk/app-release.apk"
echo ""
echo "Note: Different Android launchers (Samsung, OnePlus, etc.)"
echo "may display icons at different sizes. This is normal!"
