#!/bin/bash

# FTMS App Icon Generation Script
# This script helps generate app icons in various sizes

echo "🎨 FTMS App Icon Generation Guide (Athlete Edition)"
echo "=================================================="
echo ""
echo "We've created new SVG designs featuring an athlete working out:"
echo "- app_icon_athlete.svg (detailed version)"
echo "- app_icon_athlete_clean.svg (simplified version)"
echo "- app_icon_final_athlete.svg (RECOMMENDED - best balance)"
echo ""
echo "To generate app icons, you'll need to:"
echo ""
echo "1. Convert SVG to PNG (1024x1024):"
echo "   - Use the RECOMMENDED version: app_icon_final_athlete.svg"
echo "   - Use an online tool like https://cloudconvert.com/svg-to-png"
echo "   - Or use Inkscape: inkscape --export-png=app_icon_athlete_1024.png --export-width=1024 --export-height=1024 app_icon_final_athlete.svg"
echo "   - Save as: assets/app_icon_athlete_1024.png"
echo ""
echo "2. Install dependencies and generate icons:"
echo "   flutter pub get"
echo "   flutter pub run flutter_launcher_icons:main"
echo ""
echo "New Icon Design Features:"
echo "🏃 Athlete in rowing position (dynamic and human)"
echo "🚣 Rowing machine representation"
echo "� Prominent Bluetooth symbol (connectivity)"
echo "❤️ Heart rate indicator (fitness tracking)"
echo "⚡ Performance/speed indicator"
echo "📊 Motion lines (showing activity)"
echo ""
echo "The icon now represents:"
echo "- Real person using fitness equipment"
echo "- Active training/workout in progress"
echo "- Bluetooth connectivity to equipment"
echo "- Modern fitness app aesthetic"
echo "- Clear visibility at all icon sizes"
